disabled_rules:
  - multiple_closures_with_trailing_closure
  - todo
  - xctfail_message
  - nesting

opt_in_rules:
  - file_header
  - modifier_order
  - sorted_imports
  - unused_capture_list

trailing_comma:
    mandatory_comma: true

line_length: 180
