name: test
on:
  pull_request

jobs:
  test:
    runs-on: macos-12
    name: Test
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: |
          cd DropcastPackage
          xcodebuild -scheme Dropcast -resultBundlePath TestResults test

      - uses: kishikawakatsumi/xcresulttool@v1
        with:
          path: TestResults.xcresult
        if: always()
